version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: nestjs-backend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: npm run start:dev

volumes:
  pgdata:
